INSERT INTO companies (name, address)
VALUES ('Bubblebox', '05 Forster Lane');
INSERT INTO companies (name, address)
VALUES ('Izio', '783 Commercial Park');
INSERT INTO companies (name, address)
VALUES ('Zoozzy', '636 Monument Terrace');
INSERT INTO companies (name, address)
VALUES ('Chatterbridge', '8892 Wayridge Hill');
INSERT INTO companies (name, address)
VALUES ('Flashdog', '6269 American Ash Crossing');
INSERT INTO companies (name, address)
VALUES ('Feednation', '341 Fair Oaks Court');
INSERT INTO companies (name, address)
VALUES ('Jabberstorm', '9050 Elgar Circle');
INSERT INTO companies (name, address)
VALUES ('Divape', '7 Maple Wood Hill');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '8 Springview Lane');
INSERT INTO companies (name, address)
VALUES ('Topiclounge', '41613 Acker Place');
INSERT INTO companies (name, address)
VALUES ('Abata', '1 Hoffman Center');
INSERT INTO companies (name, address)
VALUES ('BlogXS', '40567 Reinke Road');
INSERT INTO companies (name, address)
VALUES ('Devpoint', '03 John Wall Road');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '51 Pankratz Parkway');
INSERT INTO companies (name, address)
VALUES ('Browsetype', '85 Golf Course Pass');
INSERT INTO companies (name, address)
VALUES ('Agivu', '8350 Blue Bill Park Trail');
INSERT INTO companies (name, address)
VALUES ('Realcube', '6963 Shasta Pass');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '42 Crescent Oaks Center');
INSERT INTO companies (name, address)
VALUES ('Browsezoom', '9027 6th Alley');
INSERT INTO companies (name, address)
VALUES ('Quatz', '624 Crest Line Circle');
INSERT INTO companies (name, address)
VALUES ('Twitterbeat', '11381 Carioca Street');
INSERT INTO companies (name, address)
VALUES ('Dazzlesphere', '197 Stuart Alley');
INSERT INTO companies (name, address)
VALUES ('Fatz', '5 Bartillon Terrace');
INSERT INTO companies (name, address)
VALUES ('Oyoba', '01330 Eggendart Center');
INSERT INTO companies (name, address)
VALUES ('Zoozzy', '0 Hanson Court');
INSERT INTO companies (name, address)
VALUES ('Topicshots', '9516 Westend Way');
INSERT INTO companies (name, address)
VALUES ('Quamba', '354 Everett Plaza');
INSERT INTO companies (name, address)
VALUES ('Digitube', '9757 Haas Center');
INSERT INTO companies (name, address)
VALUES ('Vipe', '94742 Ronald Regan Hill');
INSERT INTO companies (name, address)
VALUES ('Tagchat', '10796 Dottie Pass');
INSERT INTO companies (name, address)
VALUES ('Photobug', '71 6th Point');
INSERT INTO companies (name, address)
VALUES ('Riffpath', '1 West Road');
INSERT INTO companies (name, address)
VALUES ('Centidel', '1755 Forest Dale Drive');
INSERT INTO companies (name, address)
VALUES ('Bubblebox', '78 Graedel Crossing');
INSERT INTO companies (name, address)
VALUES ('Agimba', '8 Kinsman Junction');
INSERT INTO companies (name, address)
VALUES ('Edgetag', '329 Badeau Park');
INSERT INTO companies (name, address)
VALUES ('Twitterlist', '86 Esker Terrace');
INSERT INTO companies (name, address)
VALUES ('Yakijo', '84 Homewood Court');
INSERT INTO companies (name, address)
VALUES ('Meevee', '3 Northwestern Way');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '9009 Buena Vista Center');
INSERT INTO companies (name, address)
VALUES ('Skibox', '3595 Mallory Road');
INSERT INTO companies (name, address)
VALUES ('Skiptube', '5437 Farwell Trail');
INSERT INTO companies (name, address)
VALUES ('Youspan', '36 Montana Court');
INSERT INTO companies (name, address)
VALUES ('Brainbox', '26914 Kensington Terrace');
INSERT INTO companies (name, address)
VALUES ('Twitternation', '580 Grasskamp Parkway');
INSERT INTO companies (name, address)
VALUES ('Gevee', '21136 Mcbride Crossing');
INSERT INTO companies (name, address)
VALUES ('Feedfire', '39815 Heath Street');
INSERT INTO companies (name, address)
VALUES ('Yamia', '124 Veith Lane');
INSERT INTO companies (name, address)
VALUES ('Brainlounge', '855 Arkansas Point');
INSERT INTO companies (name, address)
VALUES ('Rhyloo', '2830 Scott Junction');
INSERT INTO companies (name, address)
VALUES ('Pixoboo', '3 Stoughton Road');
INSERT INTO companies (name, address)
VALUES ('Gigabox', '51 Packers Drive');
INSERT INTO companies (name, address)
VALUES ('Quire', '7 Declaration Road');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '54863 Service Junction');
INSERT INTO companies (name, address)
VALUES ('Zoovu', '869 Paget Avenue');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '94155 Bunker Hill Plaza');
INSERT INTO companies (name, address)
VALUES ('Fanoodle', '31328 Sundown Parkway');
INSERT INTO companies (name, address)
VALUES ('Tagchat', '57 Dunning Drive');
INSERT INTO companies (name, address)
VALUES ('Trudoo', '62857 Del Sol Pass');
INSERT INTO companies (name, address)
VALUES ('Pixoboo', '959 Main Way');
INSERT INTO companies (name, address)
VALUES ('Voonte', '1 Raven Crossing');
INSERT INTO companies (name, address)
VALUES ('Browsedrive', '587 Warbler Place');
INSERT INTO companies (name, address)
VALUES ('Brainbox', '9830 Blaine Alley');
INSERT INTO companies (name, address)
VALUES ('Buzzdog', '00584 Anzinger Drive');
INSERT INTO companies (name, address)
VALUES ('Skivee', '402 Utah Court');
INSERT INTO companies (name, address)
VALUES ('Skipfire', '456 Arkansas Trail');
INSERT INTO companies (name, address)
VALUES ('Wordpedia', '526 Morningstar Point');
INSERT INTO companies (name, address)
VALUES ('Yabox', '0518 Lawn Junction');
INSERT INTO companies (name, address)
VALUES ('DabZ', '89505 Sachs Point');
INSERT INTO companies (name, address)
VALUES ('Babbleblab', '7021 Cascade Lane');
INSERT INTO companies (name, address)
VALUES ('Cogidoo', '1966 Sunbrook Hill');
INSERT INTO companies (name, address)
VALUES ('Nlounge', '825 Anzinger Terrace');
INSERT INTO companies (name, address)
VALUES ('Brainverse', '86545 Lake View Pass');
INSERT INTO companies (name, address)
VALUES ('Gabcube', '0181 American Park');
INSERT INTO companies (name, address)
VALUES ('Edgepulse', '8 Lakeland Road');
INSERT INTO companies (name, address)
VALUES ('Browsecat', '2809 Hanover Place');
INSERT INTO companies (name, address)
VALUES ('Browsedrive', '928 Pine View Court');
INSERT INTO companies (name, address)
VALUES ('Topiclounge', '3 Nancy Avenue');
INSERT INTO companies (name, address)
VALUES ('Buzzster', '9384 Tony Park');
INSERT INTO companies (name, address)
VALUES ('Topdrive', '6968 Hallows Junction');
INSERT INTO companies (name, address)
VALUES ('Jaxbean', '6 Corry Plaza');
INSERT INTO companies (name, address)
VALUES ('Aivee', '3 Sherman Point');
INSERT INTO companies (name, address)
VALUES ('Youspan', '46720 Hanover Pass');
INSERT INTO companies (name, address)
VALUES ('Dablist', '53 Northwestern Terrace');
INSERT INTO companies (name, address)
VALUES ('Aimbo', '203 Blue Bill Park Court');
INSERT INTO companies (name, address)
VALUES ('Twiyo', '64 Maple Wood Drive');
INSERT INTO companies (name, address)
VALUES ('Vinte', '406 Menomonie Junction');
INSERT INTO companies (name, address)
VALUES ('Meejo', '4 Rockefeller Terrace');
INSERT INTO companies (name, address)
VALUES ('Voolith', '95 Novick Parkway');
INSERT INTO companies (name, address)
VALUES ('Oyoloo', '726 Moland Plaza');
INSERT INTO companies (name, address)
VALUES ('Twimm', '2 Maywood Point');
INSERT INTO companies (name, address)
VALUES ('Plambee', '97 Division Plaza');
INSERT INTO companies (name, address)
VALUES ('Browseblab', '20243 Garrison Road');
INSERT INTO companies (name, address)
VALUES ('Brightdog', '3 Delladonna Way');
INSERT INTO companies (name, address)
VALUES ('Buzzbean', '683 Dennis Street');
INSERT INTO companies (name, address)
VALUES ('Jaxworks', '74428 Carpenter Drive');
INSERT INTO companies (name, address)
VALUES ('Abata', '6446 Birchwood Park');
INSERT INTO companies (name, address)
VALUES ('Skynoodle', '75 Manley Terrace');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '39 Independence Hill');
INSERT INTO companies (name, address)
VALUES ('Tagpad', '50444 Bunting Lane');
INSERT INTO companies (name, address)
VALUES ('Pixoboo', '447 Morning Plaza');
INSERT INTO companies (name, address)
VALUES ('Zazio', '8 Northview Place');
INSERT INTO companies (name, address)
VALUES ('Zoombeat', '21 Pepper Wood Circle');
INSERT INTO companies (name, address)
VALUES ('Jaxnation', '53 Hoffman Alley');
INSERT INTO companies (name, address)
VALUES ('Oyoba', '4 Spenser Drive');
INSERT INTO companies (name, address)
VALUES ('Meeveo', '58 Schiller Terrace');
INSERT INTO companies (name, address)
VALUES ('Divanoodle', '8 Gale Point');
INSERT INTO companies (name, address)
VALUES ('Babbleblab', '60696 Lakewood Gardens Circle');
INSERT INTO companies (name, address)
VALUES ('Buzzdog', '831 Dakota Street');
INSERT INTO companies (name, address)
VALUES ('Tavu', '6432 North Alley');
INSERT INTO companies (name, address)
VALUES ('Thoughtworks', '4611 Lotheville Road');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '28 Crowley Circle');
INSERT INTO companies (name, address)
VALUES ('Skajo', '7723 Mandrake Drive');
INSERT INTO companies (name, address)
VALUES ('Edgeblab', '16301 Stuart Hill');
INSERT INTO companies (name, address)
VALUES ('Jazzy', '0 Village Point');
INSERT INTO companies (name, address)
VALUES ('Vinte', '3 Eastwood Trail');
INSERT INTO companies (name, address)
VALUES ('Fivebridge', '15 Eagle Crest Road');
INSERT INTO companies (name, address)
VALUES ('Rhynoodle', '064 Wayridge Crossing');
INSERT INTO companies (name, address)
VALUES ('Tekfly', '3 Pankratz Circle');
INSERT INTO companies (name, address)
VALUES ('Ntags', '084 Sachtjen Way');
INSERT INTO companies (name, address)
VALUES ('Zoomdog', '3 Old Shore Terrace');
INSERT INTO companies (name, address)
VALUES ('Devify', '514 Derek Circle');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '7419 Talmadge Road');
INSERT INTO companies (name, address)
VALUES ('Minyx', '49 Heffernan Place');
INSERT INTO companies (name, address)
VALUES ('Trilia', '06149 Coolidge Terrace');
INSERT INTO companies (name, address)
VALUES ('Wordware', '0718 Golden Leaf Center');
INSERT INTO companies (name, address)
VALUES ('Dynava', '6649 Carpenter Drive');
INSERT INTO companies (name, address)
VALUES ('Fadeo', '7 Reindahl Crossing');
INSERT INTO companies (name, address)
VALUES ('Lajo', '4 Donald Street');
INSERT INTO companies (name, address)
VALUES ('Browsecat', '4268 Sunfield Trail');
INSERT INTO companies (name, address)
VALUES ('Lajo', '71 Cascade Drive');
INSERT INTO companies (name, address)
VALUES ('Devify', '4867 Logan Point');
INSERT INTO companies (name, address)
VALUES ('Vipe', '083 Delaware Crossing');
INSERT INTO companies (name, address)
VALUES ('Quimba', '842 5th Drive');
INSERT INTO companies (name, address)
VALUES ('Wordware', '8 Claremont Point');
INSERT INTO companies (name, address)
VALUES ('Brainsphere', '72 Mockingbird Hill');
INSERT INTO companies (name, address)
VALUES ('Fivebridge', '14297 Redwing Place');
INSERT INTO companies (name, address)
VALUES ('Babbleopia', '22737 North Avenue');
INSERT INTO companies (name, address)
VALUES ('Photobean', '0 Bobwhite Way');
INSERT INTO companies (name, address)
VALUES ('Yozio', '085 Norway Maple Place');
INSERT INTO companies (name, address)
VALUES ('Buzzbean', '46209 Magdeline Pass');
INSERT INTO companies (name, address)
VALUES ('Cogilith', '92 Fieldstone Circle');
INSERT INTO companies (name, address)
VALUES ('Lajo', '0603 Ludington Road');
INSERT INTO companies (name, address)
VALUES ('Ozu', '07 Almo Parkway');
INSERT INTO companies (name, address)
VALUES ('Fliptune', '5 Steensland Point');
INSERT INTO companies (name, address)
VALUES ('Yata', '3 Hanson Pass');
INSERT INTO companies (name, address)
VALUES ('Zoonoodle', '935 Esch Avenue');
INSERT INTO companies (name, address)
VALUES ('Photobug', '1116 Onsgard Junction');
INSERT INTO companies (name, address)
VALUES ('Wordtune', '865 Kingsford Road');
INSERT INTO companies (name, address)
VALUES ('Twiyo', '7760 Drewry Pass');
INSERT INTO companies (name, address)
VALUES ('Camimbo', '8464 Mendota Alley');
INSERT INTO companies (name, address)
VALUES ('Eimbee', '8 Messerschmidt Place');
INSERT INTO companies (name, address)
VALUES ('Lazz', '92 Annamark Trail');
INSERT INTO companies (name, address)
VALUES ('Dabvine', '0897 Eastlawn Hill');
INSERT INTO companies (name, address)
VALUES ('Photolist', '17 Transport Lane');
INSERT INTO companies (name, address)
VALUES ('Dabshots', '85 Lighthouse Bay Terrace');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '31799 Claremont Point');
INSERT INTO companies (name, address)
VALUES ('Meemm', '72549 Ryan Trail');
INSERT INTO companies (name, address)
VALUES ('Cogilith', '8586 Menomonie Place');
INSERT INTO companies (name, address)
VALUES ('Feedspan', '4970 Sycamore Park');
INSERT INTO companies (name, address)
VALUES ('Blogpad', '1602 Packers Plaza');
INSERT INTO companies (name, address)
VALUES ('Tagpad', '93 Susan Plaza');
INSERT INTO companies (name, address)
VALUES ('Photolist', '86853 Stone Corner Hill');
INSERT INTO companies (name, address)
VALUES ('Flashdog', '8 Ronald Regan Parkway');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '40 Donald Hill');
INSERT INTO companies (name, address)
VALUES ('Photofeed', '77161 Heath Way');
INSERT INTO companies (name, address)
VALUES ('Leexo', '0737 Eggendart Hill');
INSERT INTO companies (name, address)
VALUES ('Fiveclub', '82 Kings Trail');
INSERT INTO companies (name, address)
VALUES ('Kwideo', '52315 Pawling Court');
INSERT INTO companies (name, address)
VALUES ('Rhyloo', '5 Mayer Parkway');
INSERT INTO companies (name, address)
VALUES ('Oyope', '413 Mendota Court');
INSERT INTO companies (name, address)
VALUES ('Feedfish', '7 Service Parkway');
INSERT INTO companies (name, address)
VALUES ('Zoozzy', '57 Dwight Court');
INSERT INTO companies (name, address)
VALUES ('Riffwire', '843 Bellgrove Way');
INSERT INTO companies (name, address)
VALUES ('Voolith', '0 Spohn Avenue');
INSERT INTO companies (name, address)
VALUES ('Thoughtsphere', '07180 Monterey Way');
INSERT INTO companies (name, address)
VALUES ('Yadel', '9282 Brown Center');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '3921 Bobwhite Pass');
INSERT INTO companies (name, address)
VALUES ('Fadeo', '20 Nobel Road');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '6 8th Avenue');
INSERT INTO companies (name, address)
VALUES ('Leexo', '4 Goodland Alley');
INSERT INTO companies (name, address)
VALUES ('Youtags', '2 Waywood Terrace');
INSERT INTO companies (name, address)
VALUES ('Eayo', '30498 Huxley Pass');
INSERT INTO companies (name, address)
VALUES ('Yoveo', '35005 Toban Parkway');
INSERT INTO companies (name, address)
VALUES ('Divavu', '0191 Springview Center');
INSERT INTO companies (name, address)
VALUES ('Thoughtstorm', '5 Melvin Trail');
INSERT INTO companies (name, address)
VALUES ('Gevee', '949 Kensington Lane');
INSERT INTO companies (name, address)
VALUES ('Oyondu', '6 Vermont Park');
INSERT INTO companies (name, address)
VALUES ('Bluejam', '31 Fulton Alley');
INSERT INTO companies (name, address)
VALUES ('Gigaclub', '023 Veith Point');
INSERT INTO companies (name, address)
VALUES ('Brainsphere', '14561 Dawn Alley');
INSERT INTO companies (name, address)
VALUES ('Roomm', '40960 Kinsman Pass');
INSERT INTO companies (name, address)
VALUES ('Buzzster', '248 Sachtjen Parkway');
INSERT INTO companies (name, address)
VALUES ('Katz', '574 Anderson Center');
INSERT INTO companies (name, address)
VALUES ('Thoughtbeat', '7 Morningstar Park');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '975 Westend Court');
INSERT INTO companies (name, address)
VALUES ('Skibox', '2 Ridge Oak Place');
INSERT INTO companies (name, address)
VALUES ('Skinder', '45 Cordelia Terrace');
INSERT INTO companies (name, address)
VALUES ('Topdrive', '195 Hintze Crossing');
INSERT INTO companies (name, address)
VALUES ('Yacero', '41 Dottie Center');
INSERT INTO companies (name, address)
VALUES ('Kwideo', '16 Dottie Trail');
INSERT INTO companies (name, address)
VALUES ('Avamm', '3388 Kensington Road');
INSERT INTO companies (name, address)
VALUES ('Leexo', '82 Dunning Circle');
INSERT INTO companies (name, address)
VALUES ('Skidoo', '126 Meadow Valley Point');
INSERT INTO companies (name, address)
VALUES ('Rhyzio', '22 East Court');
INSERT INTO companies (name, address)
VALUES ('Thoughtmix', '2 Manufacturers Alley');
INSERT INTO companies (name, address)
VALUES ('Rhycero', '07 Welch Parkway');
INSERT INTO companies (name, address)
VALUES ('Dabvine', '98325 Artisan Point');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '00057 Monument Crossing');
INSERT INTO companies (name, address)
VALUES ('Youopia', '01462 Darwin Street');
INSERT INTO companies (name, address)
VALUES ('Devpoint', '4 Mccormick Way');
INSERT INTO companies (name, address)
VALUES ('Skyvu', '43 Jenifer Court');
INSERT INTO companies (name, address)
VALUES ('Snaptags', '50 Carioca Trail');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '041 Thierer Terrace');
INSERT INTO companies (name, address)
VALUES ('Katz', '486 6th Hill');
INSERT INTO companies (name, address)
VALUES ('Rooxo', '04 Corry Terrace');
INSERT INTO companies (name, address)
VALUES ('Snaptags', '73 Coleman Terrace');
INSERT INTO companies (name, address)
VALUES ('Topdrive', '73 Dovetail Street');
INSERT INTO companies (name, address)
VALUES ('Roodel', '7284 Lakewood Gardens Point');
INSERT INTO companies (name, address)
VALUES ('Shuffletag', '6 Superior Trail');
INSERT INTO companies (name, address)
VALUES ('Trudeo', '116 Moland Park');
INSERT INTO companies (name, address)
VALUES ('Vimbo', '52 Eastwood Place');
INSERT INTO companies (name, address)
VALUES ('Kayveo', '026 Melby Trail');
INSERT INTO companies (name, address)
VALUES ('Livefish', '3576 Warbler Drive');
INSERT INTO companies (name, address)
VALUES ('Skalith', '917 Moulton Pass');
INSERT INTO companies (name, address)
VALUES ('Meetz', '08351 Weeping Birch Lane');
INSERT INTO companies (name, address)
VALUES ('Agimba', '09311 Knutson Junction');
INSERT INTO companies (name, address)
VALUES ('Jaxworks', '00885 Fremont Junction');
INSERT INTO companies (name, address)
VALUES ('Quinu', '188 Evergreen Pass');
INSERT INTO companies (name, address)
VALUES ('Demizz', '22 Brown Plaza');
INSERT INTO companies (name, address)
VALUES ('Wikido', '69 Vidon Street');
INSERT INTO companies (name, address)
VALUES ('Browsetype', '515 Lake View Drive');
INSERT INTO companies (name, address)
VALUES ('Topiczoom', '510 Pearson Park');
INSERT INTO companies (name, address)
VALUES ('Rooxo', '6 Oak Parkway');
INSERT INTO companies (name, address)
VALUES ('Kazu', '86088 Fair Oaks Hill');
INSERT INTO companies (name, address)
VALUES ('DabZ', '2 Rowland Alley');
INSERT INTO companies (name, address)
VALUES ('Quinu', '97263 Truax Avenue');
INSERT INTO companies (name, address)
VALUES ('Oba', '193 Roth Crossing');
INSERT INTO companies (name, address)
VALUES ('Devshare', '93643 Garrison Crossing');
INSERT INTO companies (name, address)
VALUES ('Gigashots', '30680 Meadow Ridge Avenue');
INSERT INTO companies (name, address)
VALUES ('Abata', '85 Gerald Lane');
INSERT INTO companies (name, address)
VALUES ('Topicware', '60799 Superior Center');
INSERT INTO companies (name, address)
VALUES ('Oyope', '4805 Buena Vista Hill');
INSERT INTO companies (name, address)
VALUES ('Vipe', '14283 Schmedeman Lane');
INSERT INTO companies (name, address)
VALUES ('Jabbersphere', '826 Mallard Place');
INSERT INTO companies (name, address)
VALUES ('Riffpath', '2015 Sherman Hill');
INSERT INTO companies (name, address)
VALUES ('Vinte', '7895 Service Parkway');
INSERT INTO companies (name, address)
VALUES ('Wordpedia', '3 Ridgeview Lane');
INSERT INTO companies (name, address)
VALUES ('Gabvine', '62190 Westerfield Point');
INSERT INTO companies (name, address)
VALUES ('Kazu', '1319 Oriole Crossing');
INSERT INTO companies (name, address)
VALUES ('Aimbu', '2177 Crowley Alley');
INSERT INTO companies (name, address)
VALUES ('Gigabox', '7535 Nobel Parkway');
INSERT INTO companies (name, address)
VALUES ('Fivespan', '552 Brickson Park Trail');
INSERT INTO companies (name, address)
VALUES ('Pixope', '7446 International Junction');
INSERT INTO companies (name, address)
VALUES ('Youspan', '364 Independence Circle');
INSERT INTO companies (name, address)
VALUES ('Zoonder', '63753 Browning Place');
INSERT INTO companies (name, address)
VALUES ('Yabox', '480 Chinook Trail');
INSERT INTO companies (name, address)
VALUES ('Trudoo', '81 Village Trail');
INSERT INTO companies (name, address)
VALUES ('Youfeed', '5207 Red Cloud Hill');
INSERT INTO companies (name, address)
VALUES ('Rhybox', '23 Dakota Street');
INSERT INTO companies (name, address)
VALUES ('Dynabox', '2 Kingsford Hill');
INSERT INTO companies (name, address)
VALUES ('Dabjam', '53602 Sutteridge Circle');
INSERT INTO companies (name, address)
VALUES ('Babbleblab', '0 Becker Plaza');
INSERT INTO companies (name, address)
VALUES ('Skyble', '12 Emmet Avenue');
INSERT INTO companies (name, address)
VALUES ('Riffwire', '65496 Ludington Plaza');
INSERT INTO companies (name, address)
VALUES ('Topdrive', '533 Dennis Crossing');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '703 Dwight Pass');
INSERT INTO companies (name, address)
VALUES ('Shufflester', '394 Ryan Terrace');
INSERT INTO companies (name, address)
VALUES ('Youspan', '8 Claremont Street');
INSERT INTO companies (name, address)
VALUES ('Twitterbeat', '065 Sugar Hill');
INSERT INTO companies (name, address)
VALUES ('Dynava', '41853 Menomonie Court');
INSERT INTO companies (name, address)
VALUES ('Lajo', '535 Mifflin Circle');
INSERT INTO companies (name, address)
VALUES ('Eire', '1 Browning Place');
INSERT INTO companies (name, address)
VALUES ('Thoughtstorm', '0 Dottie Terrace');
INSERT INTO companies (name, address)
VALUES ('Edgetag', '7502 Mendota Court');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '4 Straubel Parkway');
INSERT INTO companies (name, address)
VALUES ('Demizz', '09 Eastwood Trail');
INSERT INTO companies (name, address)
VALUES ('Voolia', '7371 Westridge Pass');
INSERT INTO companies (name, address)
VALUES ('Topiczoom', '5 Hoard Place');
INSERT INTO companies (name, address)
VALUES ('Podcat', '0 Tennessee Junction');
INSERT INTO companies (name, address)
VALUES ('Buzzbean', '37 Namekagon Terrace');
INSERT INTO companies (name, address)
VALUES ('Twinder', '418 Browning Terrace');
INSERT INTO companies (name, address)
VALUES ('Agivu', '925 2nd Way');
INSERT INTO companies (name, address)
VALUES ('Meezzy', '934 Anniversary Parkway');
INSERT INTO companies (name, address)
VALUES ('Realmix', '97475 Kinsman Park');
INSERT INTO companies (name, address)
VALUES ('Skipstorm', '11 Knutson Hill');
INSERT INTO companies (name, address)
VALUES ('Vitz', '9 Ohio Pass');
INSERT INTO companies (name, address)
VALUES ('Tazzy', '25314 Buhler Way');
INSERT INTO companies (name, address)
VALUES ('Jetwire', '10706 Myrtle Pass');
INSERT INTO companies (name, address)
VALUES ('Rhyloo', '8595 Montana Place');
INSERT INTO companies (name, address)
VALUES ('Youspan', '39555 Mcbride Court');
INSERT INTO companies (name, address)
VALUES ('Zoombox', '43 Lukken Lane');
INSERT INTO companies (name, address)
VALUES ('Riffpedia', '1097 Mallory Plaza');
INSERT INTO companies (name, address)
VALUES ('Yakitri', '6 Portage Hill');
INSERT INTO companies (name, address)
VALUES ('Gigashots', '7769 Maywood Circle');
INSERT INTO companies (name, address)
VALUES ('Skyndu', '203 Ridge Oak Court');
INSERT INTO companies (name, address)
VALUES ('Realmix', '9 Eastlawn Parkway');
INSERT INTO companies (name, address)
VALUES ('Realmix', '2972 Riverside Court');
INSERT INTO companies (name, address)
VALUES ('Fivespan', '04264 Elgar Drive');
INSERT INTO companies (name, address)
VALUES ('Realcube', '4 Meadow Valley Hill');
INSERT INTO companies (name, address)
VALUES ('Agivu', '8621 Stoughton Circle');
INSERT INTO companies (name, address)
VALUES ('Agimba', '69 Parkside Way');
INSERT INTO companies (name, address)
VALUES ('Vimbo', '55696 Stuart Road');
INSERT INTO companies (name, address)
VALUES ('Skyndu', '6 Dwight Court');
INSERT INTO companies (name, address)
VALUES ('Ntags', '42 Main Place');
INSERT INTO companies (name, address)
VALUES ('Skimia', '36 Badeau Avenue');
INSERT INTO companies (name, address)
VALUES ('Myworks', '230 Hazelcrest Terrace');
INSERT INTO companies (name, address)
VALUES ('Oyope', '542 Clyde Gallagher Center');
INSERT INTO companies (name, address)
VALUES ('Vinder', '520 Grasskamp Way');
INSERT INTO companies (name, address)
VALUES ('Skyndu', '07661 Dennis Circle');
INSERT INTO companies (name, address)
VALUES ('Tagtune', '00 Prairieview Crossing');
INSERT INTO companies (name, address)
VALUES ('Kare', '7470 Tomscot Place');
INSERT INTO companies (name, address)
VALUES ('Flipbug', '91516 Bunker Hill Center');
INSERT INTO companies (name, address)
VALUES ('Eayo', '6781 Acker Parkway');
INSERT INTO companies (name, address)
VALUES ('Kwideo', '85 Michigan Place');
INSERT INTO companies (name, address)
VALUES ('Yambee', '29087 Doe Crossing Lane');
INSERT INTO companies (name, address)
VALUES ('Zava', '4264 Valley Edge Way');
INSERT INTO companies (name, address)
VALUES ('Tagcat', '3938 Butternut Junction');
INSERT INTO companies (name, address)
VALUES ('Flashdog', '05 Express Crossing');
INSERT INTO companies (name, address)
VALUES ('Npath', '405 Pine View Park');
INSERT INTO companies (name, address)
VALUES ('Livetube', '76 Fremont Crossing');
INSERT INTO companies (name, address)
VALUES ('Brightbean', '2 Sheridan Circle');
INSERT INTO companies (name, address)
VALUES ('Skippad', '4 Bellgrove Road');
INSERT INTO companies (name, address)
VALUES ('Avaveo', '28 Surrey Parkway');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '79832 Fordem Junction');
INSERT INTO companies (name, address)
VALUES ('Babbleopia', '064 Sunfield Pass');
INSERT INTO companies (name, address)
VALUES ('Quimba', '1 Calypso Pass');
INSERT INTO companies (name, address)
VALUES ('Vipe', '09 Butterfield Road');
INSERT INTO companies (name, address)
VALUES ('Yotz', '32424 Cody Junction');
INSERT INTO companies (name, address)
VALUES ('Avamba', '1 Morningstar Street');
INSERT INTO companies (name, address)
VALUES ('Ainyx', '150 Banding Alley');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '0637 Monterey Point');
INSERT INTO companies (name, address)
VALUES ('Meembee', '855 Hermina Crossing');
INSERT INTO companies (name, address)
VALUES ('Oyondu', '41 Shelley Lane');
INSERT INTO companies (name, address)
VALUES ('Eabox', '69 Gateway Terrace');
INSERT INTO companies (name, address)
VALUES ('Gabspot', '27 8th Hill');
INSERT INTO companies (name, address)
VALUES ('Realcube', '47 Brickson Park Trail');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '491 Toban Road');
INSERT INTO companies (name, address)
VALUES ('Meejo', '861 Westend Lane');
INSERT INTO companies (name, address)
VALUES ('Vinte', '7386 Green Road');
INSERT INTO companies (name, address)
VALUES ('Rhycero', '62 Blue Bill Park Center');
INSERT INTO companies (name, address)
VALUES ('Rhynoodle', '656 Lerdahl Hill');
INSERT INTO companies (name, address)
VALUES ('Nlounge', '8013 Gulseth Junction');
INSERT INTO companies (name, address)
VALUES ('Innotype', '45447 Cottonwood Parkway');
INSERT INTO companies (name, address)
VALUES ('Aivee', '3731 West Junction');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '869 Lien Parkway');
INSERT INTO companies (name, address)
VALUES ('Skimia', '92064 John Wall Crossing');
INSERT INTO companies (name, address)
VALUES ('Meedoo', '7339 Moose Street');
INSERT INTO companies (name, address)
VALUES ('Jayo', '0 Pawling Point');
INSERT INTO companies (name, address)
VALUES ('Myworks', '0204 Dixon Hill');
INSERT INTO companies (name, address)
VALUES ('Skidoo', '67586 Susan Place');
INSERT INTO companies (name, address)
VALUES ('Wordpedia', '667 Crowley Pass');
INSERT INTO companies (name, address)
VALUES ('Tagfeed', '105 Lakewood Center');
INSERT INTO companies (name, address)
VALUES ('Livetube', '85 Upham Trail');
INSERT INTO companies (name, address)
VALUES ('Zoombox', '45 Roxbury Drive');
INSERT INTO companies (name, address)
VALUES ('Riffpedia', '508 Portage Plaza');
INSERT INTO companies (name, address)
VALUES ('Kazio', '7 Charing Cross Junction');
INSERT INTO companies (name, address)
VALUES ('Lazz', '1 Oneill Drive');
INSERT INTO companies (name, address)
VALUES ('Ainyx', '00070 Birchwood Road');
INSERT INTO companies (name, address)
VALUES ('Blogtag', '31670 Service Alley');
INSERT INTO companies (name, address)
VALUES ('Quatz', '587 Holmberg Point');
INSERT INTO companies (name, address)
VALUES ('BlogXS', '25656 Declaration Place');
INSERT INTO companies (name, address)
VALUES ('Brainlounge', '311 Park Meadow Terrace');
INSERT INTO companies (name, address)
VALUES ('Dabshots', '810 Sherman Way');
INSERT INTO companies (name, address)
VALUES ('Meedoo', '12849 Melby Avenue');
INSERT INTO companies (name, address)
VALUES ('Izio', '9 Graceland Place');
INSERT INTO companies (name, address)
VALUES ('Meembee', '2 Southridge Drive');
INSERT INTO companies (name, address)
VALUES ('Oyoba', '1233 Onsgard Parkway');
INSERT INTO companies (name, address)
VALUES ('Oyoyo', '9 Lukken Park');
INSERT INTO companies (name, address)
VALUES ('Voonte', '532 Dryden Circle');
INSERT INTO companies (name, address)
VALUES ('Jaxnation', '43790 Helena Plaza');
INSERT INTO companies (name, address)
VALUES ('Vinte', '398 Mallard Plaza');
INSERT INTO companies (name, address)
VALUES ('Pixoboo', '5423 Lyons Circle');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '1934 Mesta Lane');
INSERT INTO companies (name, address)
VALUES ('Quaxo', '87 Delladonna Alley');
INSERT INTO companies (name, address)
VALUES ('Quinu', '36200 Village Place');
INSERT INTO companies (name, address)
VALUES ('Kwimbee', '839 Prairieview Court');
INSERT INTO companies (name, address)
VALUES ('Skivee', '04 Delaware Hill');
INSERT INTO companies (name, address)
VALUES ('Zoombeat', '36388 Grim Crossing');
INSERT INTO companies (name, address)
VALUES ('Skipfire', '09346 Oxford Junction');
INSERT INTO companies (name, address)
VALUES ('Oodoo', '68 Heath Center');
INSERT INTO companies (name, address)
VALUES ('Mynte', '37855 Russell Alley');
INSERT INTO companies (name, address)
VALUES ('Oloo', '2249 Arizona Circle');
INSERT INTO companies (name, address)
VALUES ('Photobug', '00138 Butternut Alley');
INSERT INTO companies (name, address)
VALUES ('Realcube', '98 Oakridge Plaza');
INSERT INTO companies (name, address)
VALUES ('Cogilith', '26 Menomonie Terrace');
INSERT INTO companies (name, address)
VALUES ('Mybuzz', '55 Pierstorff Center');
INSERT INTO companies (name, address)
VALUES ('Realcube', '0 Center Avenue');
INSERT INTO companies (name, address)
VALUES ('Leenti', '703 Dahle Drive');
INSERT INTO companies (name, address)
VALUES ('Mydo', '755 Upham Center');
INSERT INTO companies (name, address)
VALUES ('Topiclounge', '76506 Weeping Birch Way');
INSERT INTO companies (name, address)
VALUES ('Twimm', '3662 Schlimgen Alley');
INSERT INTO companies (name, address)
VALUES ('Aimbo', '86 Scofield Center');
INSERT INTO companies (name, address)
VALUES ('Katz', '5 Twin Pines Drive');
INSERT INTO companies (name, address)
VALUES ('Realcube', '755 Comanche Center');
INSERT INTO companies (name, address)
VALUES ('Jabbersphere', '7 Morning Alley');
INSERT INTO companies (name, address)
VALUES ('Riffwire', '4 Acker Center');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '76368 Schlimgen Hill');
INSERT INTO companies (name, address)
VALUES ('Brainsphere', '0095 Buhler Road');
INSERT INTO companies (name, address)
VALUES ('Yozio', '66 Manitowish Trail');
INSERT INTO companies (name, address)
VALUES ('Quatz', '01345 Utah Circle');
INSERT INTO companies (name, address)
VALUES ('Divavu', '255 Declaration Place');
INSERT INTO companies (name, address)
VALUES ('Agimba', '040 Fremont Road');
INSERT INTO companies (name, address)
VALUES ('Wordtune', '20 Schlimgen Park');
INSERT INTO companies (name, address)
VALUES ('Plambee', '3 Schiller Road');
INSERT INTO companies (name, address)
VALUES ('Dabjam', '2943 Eastlawn Crossing');
INSERT INTO companies (name, address)
VALUES ('Ooba', '8 Clyde Gallagher Court');
INSERT INTO companies (name, address)
VALUES ('Oyonder', '13974 Ryan Place');
INSERT INTO companies (name, address)
VALUES ('Photolist', '4 Vera Trail');
INSERT INTO companies (name, address)
VALUES ('Chatterbridge', '21 Sundown Avenue');
INSERT INTO companies (name, address)
VALUES ('Photofeed', '5977 Westport Avenue');
INSERT INTO companies (name, address)
VALUES ('Jabbersphere', '50 Coleman Center');
INSERT INTO companies (name, address)
VALUES ('Janyx', '52 Sage Circle');
INSERT INTO companies (name, address)
VALUES ('Kamba', '7 Trailsway Hill');
INSERT INTO companies (name, address)
VALUES ('Jabbersphere', '046 Anzinger Plaza');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '48 Victoria Trail');
INSERT INTO companies (name, address)
VALUES ('Gevee', '05 Arapahoe Hill');
INSERT INTO companies (name, address)
VALUES ('Oyoyo', '49 Dunning Lane');
INSERT INTO companies (name, address)
VALUES ('Oyonder', '29 Westport Court');
INSERT INTO companies (name, address)
VALUES ('Wordify', '2 Susan Trail');
INSERT INTO companies (name, address)
VALUES ('Zoomdog', '8 American Ash Center');
INSERT INTO companies (name, address)
VALUES ('Eayo', '4 Rowland Alley');
INSERT INTO companies (name, address)
VALUES ('LiveZ', '25555 Hovde Drive');
INSERT INTO companies (name, address)
VALUES ('Wordtune', '0663 Judy Center');
INSERT INTO companies (name, address)
VALUES ('Youfeed', '7414 Hallows Court');
INSERT INTO companies (name, address)
VALUES ('Yakijo', '87 Sachtjen Drive');
INSERT INTO companies (name, address)
VALUES ('Quatz', '62375 Vera Circle');
INSERT INTO companies (name, address)
VALUES ('Wikibox', '31795 Dottie Circle');
INSERT INTO companies (name, address)
VALUES ('Photobug', '42847 Westend Pass');
INSERT INTO companies (name, address)
VALUES ('Bluezoom', '11 Browning Terrace');
INSERT INTO companies (name, address)
VALUES ('Skimia', '0 Fairfield Point');
INSERT INTO companies (name, address)
VALUES ('Gabvine', '31 Lakewood Gardens Drive');
INSERT INTO companies (name, address)
VALUES ('Fivespan', '4972 Kennedy Court');
INSERT INTO companies (name, address)
VALUES ('Feedmix', '05341 Westridge Pass');
INSERT INTO companies (name, address)
VALUES ('Topicstorm', '95230 Valley Edge Road');
INSERT INTO companies (name, address)
VALUES ('Ntag', '63 Onsgard Pass');
INSERT INTO companies (name, address)
VALUES ('Blogpad', '38 Kinsman Center');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '57 Steensland Hill');
INSERT INTO companies (name, address)
VALUES ('Voomm', '2111 Columbus Way');
INSERT INTO companies (name, address)
VALUES ('Jatri', '4672 Doe Crossing Place');
INSERT INTO companies (name, address)
VALUES ('Thoughtbridge', '4 Sullivan Court');
INSERT INTO companies (name, address)
VALUES ('Vinder', '33 Hallows Place');
INSERT INTO companies (name, address)
VALUES ('Yabox', '823 Arkansas Hill');
INSERT INTO companies (name, address)
VALUES ('Tagpad', '9922 Eagle Crest Terrace');
INSERT INTO companies (name, address)
VALUES ('Kazio', '9 Clarendon Park');
INSERT INTO companies (name, address)
VALUES ('Yamia', '3931 Doe Crossing Trail');
INSERT INTO companies (name, address)
VALUES ('Riffpedia', '4 Sage Place');
INSERT INTO companies (name, address)
VALUES ('Kwideo', '7680 Kedzie Court');
INSERT INTO companies (name, address)
VALUES ('Meetz', '62 Del Mar Trail');
INSERT INTO companies (name, address)
VALUES ('Jabbersphere', '36151 Artisan Junction');
INSERT INTO companies (name, address)
VALUES ('Zoovu', '179 Killdeer Trail');
INSERT INTO companies (name, address)
VALUES ('Roombo', '514 Village Green Park');
INSERT INTO companies (name, address)
VALUES ('Kamba', '99 Butternut Hill');
INSERT INTO companies (name, address)
VALUES ('Skyba', '0921 Marquette Avenue');
INSERT INTO companies (name, address)
VALUES ('Realblab', '37 Autumn Leaf Place');
INSERT INTO companies (name, address)
VALUES ('Zoonoodle', '89 Forster Terrace');
INSERT INTO companies (name, address)
VALUES ('DabZ', '572 Talisman Avenue');
INSERT INTO companies (name, address)
VALUES ('Agivu', '498 Bartillon Terrace');
INSERT INTO companies (name, address)
VALUES ('Fliptune', '740 Daystar Court');
INSERT INTO companies (name, address)
VALUES ('Twitterbridge', '3930 Barby Crossing');
INSERT INTO companies (name, address)
VALUES ('Thoughtblab', '23066 Victoria Pass');
INSERT INTO companies (name, address)
VALUES ('Blogspan', '7 Ridgeway Center');
INSERT INTO companies (name, address)
VALUES ('Browseblab', '0976 Anhalt Road');
INSERT INTO companies (name, address)
VALUES ('Skyba', '76414 Nevada Avenue');
INSERT INTO companies (name, address)
VALUES ('Flashpoint', '20 Luster Pass');
INSERT INTO companies (name, address)
VALUES ('Zava', '868 Upham Way');
INSERT INTO companies (name, address)
VALUES ('Feedmix', '4688 Merry Park');
INSERT INTO companies (name, address)
VALUES ('Mymm', '98 Oak Parkway');
INSERT INTO companies (name, address)
VALUES ('Edgetag', '7615 Old Gate Alley');
INSERT INTO companies (name, address)
VALUES ('Tanoodle', '126 Pond Point');
INSERT INTO companies (name, address)
VALUES ('Wikivu', '111 Sugar Trail');
INSERT INTO companies (name, address)
VALUES ('Buzzster', '94 Golden Leaf Pass');
INSERT INTO companies (name, address)
VALUES ('Zoomdog', '673 Transport Circle');
INSERT INTO companies (name, address)
VALUES ('Skinix', '9 Cardinal Pass');
INSERT INTO companies (name, address)
VALUES ('Centimia', '51 Mayer Terrace');
INSERT INTO companies (name, address)
VALUES ('Flashdog', '069 Harper Street');
INSERT INTO companies (name, address)
VALUES ('Jabbercube', '6 Hansons Park');
INSERT INTO companies (name, address)
VALUES ('Fivebridge', '55557 Buena Vista Court');
INSERT INTO companies (name, address)
VALUES ('Oyoba', '80 Forster Place');
INSERT INTO companies (name, address)
VALUES ('Trudeo', '6230 Pleasure Street');
INSERT INTO companies (name, address)
VALUES ('Yambee', '214 Buell Pass');
INSERT INTO companies (name, address)
VALUES ('Skimia', '37839 Banding Circle');
INSERT INTO companies (name, address)
VALUES ('Viva', '8846 Columbus Crossing');
INSERT INTO companies (name, address)
VALUES ('Trupe', '64 Dahle Lane');
INSERT INTO companies (name, address)
VALUES ('Edgepulse', '53 American Ash Road');
INSERT INTO companies (name, address)
VALUES ('Kanoodle', '46847 Waywood Alley');
INSERT INTO companies (name, address)
VALUES ('Zoomlounge', '0 Oriole Circle');
INSERT INTO companies (name, address)
VALUES ('Youopia', '68 Vahlen Junction');
INSERT INTO companies (name, address)
VALUES ('Latz', '58366 Service Alley');
INSERT INTO companies (name, address)
VALUES ('Quinu', '89 Onsgard Crossing');
INSERT INTO companies (name, address)
VALUES ('Oyondu', '3832 Loomis Road');
INSERT INTO companies (name, address)
VALUES ('Plambee', '977 Alpine Circle');
INSERT INTO companies (name, address)
VALUES ('BlogXS', '6 Summit Pass');
INSERT INTO companies (name, address)
VALUES ('Linkbridge', '662 Gateway Crossing');
INSERT INTO companies (name, address)
VALUES ('Zoombox', '476 Ryan Parkway');
INSERT INTO companies (name, address)
VALUES ('Zooveo', '850 Sutteridge Hill');
INSERT INTO companies (name, address)
VALUES ('Jetpulse', '9695 Pennsylvania Drive');
INSERT INTO companies (name, address)
VALUES ('Camido', '42 Judy Alley');
INSERT INTO companies (name, address)
VALUES ('Gigaclub', '8 Golden Leaf Junction');
INSERT INTO companies (name, address)
VALUES ('Avamm', '22 Utah Place');
INSERT INTO companies (name, address)
VALUES ('Mita', '863 Southridge Street');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '0108 Riverside Place');
INSERT INTO companies (name, address)
VALUES ('Buzzshare', '14 Heath Lane');
INSERT INTO companies (name, address)
VALUES ('Zoombox', '8746 Stang Park');
INSERT INTO companies (name, address)
VALUES ('Jaloo', '44 Hovde Terrace');
INSERT INTO companies (name, address)
VALUES ('Twitterlist', '2610 North Lane');
INSERT INTO companies (name, address)
VALUES ('Topiczoom', '476 Swallow Drive');
INSERT INTO companies (name, address)
VALUES ('Tekfly', '3786 Summerview Plaza');
INSERT INTO companies (name, address)
VALUES ('Jetpulse', '7 Talisman Hill');
INSERT INTO companies (name, address)
VALUES ('Realcube', '2550 Texas Avenue');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '88 Pleasure Plaza');
INSERT INTO companies (name, address)
VALUES ('Trunyx', '79 Butterfield Point');
INSERT INTO companies (name, address)
VALUES ('Latz', '07352 Manley Avenue');
INSERT INTO companies (name, address)
VALUES ('Voomm', '79280 Green Circle');
INSERT INTO companies (name, address)
VALUES ('Voomm', '984 Lakewood Gardens Court');
INSERT INTO companies (name, address)
VALUES ('Zava', '26945 Hayes Place');
INSERT INTO companies (name, address)
VALUES ('Voomm', '1816 Carey Plaza');
INSERT INTO companies (name, address)
VALUES ('Pixope', '881 Lakeland Court');
INSERT INTO companies (name, address)
VALUES ('Twitterworks', '29432 Becker Terrace');
INSERT INTO companies (name, address)
VALUES ('Thoughtstorm', '192 Sullivan Street');
INSERT INTO companies (name, address)
VALUES ('Meezzy', '43 Mcguire Court');
INSERT INTO companies (name, address)
VALUES ('Zoovu', '641 Di Loreto Trail');
INSERT INTO companies (name, address)
VALUES ('Browsebug', '5080 Petterle Parkway');
INSERT INTO companies (name, address)
VALUES ('Roombo', '05800 Norway Maple Point');
INSERT INTO companies (name, address)
VALUES ('Tazzy', '5575 Maple Street');
INSERT INTO companies (name, address)
VALUES ('Shuffletag', '6654 Loomis Junction');
INSERT INTO companies (name, address)
VALUES ('Oyoloo', '3801 Village Court');
INSERT INTO companies (name, address)
VALUES ('Katz', '82 Buhler Junction');
INSERT INTO companies (name, address)
VALUES ('Realcube', '92 Ridgeway Plaza');
INSERT INTO companies (name, address)
VALUES ('Livetube', '6116 Knutson Center');
INSERT INTO companies (name, address)
VALUES ('Skinix', '48875 Londonderry Drive');
INSERT INTO companies (name, address)
VALUES ('Gigashots', '3134 Caliangt Park');
INSERT INTO companies (name, address)
VALUES ('Meevee', '1018 Westport Parkway');
INSERT INTO companies (name, address)
VALUES ('Tanoodle', '5 Mcguire Trail');
INSERT INTO companies (name, address)
VALUES ('Yozio', '59 Fair Oaks Plaza');
INSERT INTO companies (name, address)
VALUES ('Vitz', '230 Spenser Point');
INSERT INTO companies (name, address)
VALUES ('Linkbuzz', '146 Hoffman Lane');
INSERT INTO companies (name, address)
VALUES ('Roombo', '3267 Sunfield Drive');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '9 Duke Street');
INSERT INTO companies (name, address)
VALUES ('Realpoint', '6 Boyd Alley');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '008 Karstens Circle');
INSERT INTO companies (name, address)
VALUES ('Twiyo', '0 Colorado Alley');
INSERT INTO companies (name, address)
VALUES ('Npath', '5111 Hoepker Street');
INSERT INTO companies (name, address)
VALUES ('DabZ', '42176 Service Road');
INSERT INTO companies (name, address)
VALUES ('Dynabox', '069 Meadow Ridge Road');
INSERT INTO companies (name, address)
VALUES ('Gigaclub', '72 Orin Junction');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '7255 Algoma Place');
INSERT INTO companies (name, address)
VALUES ('Tambee', '185 Hanover Center');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '6706 Dovetail Alley');
INSERT INTO companies (name, address)
VALUES ('Thoughtbridge', '00802 Cottonwood Terrace');
INSERT INTO companies (name, address)
VALUES ('Tagfeed', '88922 Bluejay Crossing');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '0 Shoshone Way');
INSERT INTO companies (name, address)
VALUES ('Trilia', '83 Lillian Road');
INSERT INTO companies (name, address)
VALUES ('Gigabox', '45 Gulseth Avenue');
INSERT INTO companies (name, address)
VALUES ('Meeveo', '4 Scott Pass');
INSERT INTO companies (name, address)
VALUES ('Bubblemix', '529 Dapin Drive');
INSERT INTO companies (name, address)
VALUES ('Twimbo', '3464 John Wall Alley');
INSERT INTO companies (name, address)
VALUES ('Dabfeed', '169 Sage Crossing');
INSERT INTO companies (name, address)
VALUES ('Realbridge', '6 Hazelcrest Point');
INSERT INTO companies (name, address)
VALUES ('Trudeo', '155 Northview Junction');
INSERT INTO companies (name, address)
VALUES ('Kamba', '023 Kipling Center');
INSERT INTO companies (name, address)
VALUES ('Aivee', '10429 Scott Junction');
INSERT INTO companies (name, address)
VALUES ('Meetz', '8063 Ryan Circle');
INSERT INTO companies (name, address)
VALUES ('Dynabox', '0 Heffernan Drive');
INSERT INTO companies (name, address)
VALUES ('Realfire', '25449 Tony Crossing');
INSERT INTO companies (name, address)
VALUES ('Oyondu', '1 Menomonie Point');
INSERT INTO companies (name, address)
VALUES ('Yozio', '1 2nd Place');
INSERT INTO companies (name, address)
VALUES ('Zoomzone', '4 Northport Lane');
INSERT INTO companies (name, address)
VALUES ('Buzzbean', '861 Meadow Ridge Junction');
INSERT INTO companies (name, address)
VALUES ('Yombu', '24 Buell Court');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '6 Randy Circle');
INSERT INTO companies (name, address)
VALUES ('Blognation', '35811 Macpherson Hill');
INSERT INTO companies (name, address)
VALUES ('Zoomlounge', '85759 Corscot Junction');
INSERT INTO companies (name, address)
VALUES ('Jayo', '85492 Schlimgen Street');
INSERT INTO companies (name, address)
VALUES ('Agimba', '09 Paget Trail');
INSERT INTO companies (name, address)
VALUES ('Devpulse', '0 Anzinger Court');
INSERT INTO companies (name, address)
VALUES ('Agivu', '36 Hermina Point');
INSERT INTO companies (name, address)
VALUES ('Bubblemix', '47603 Monument Circle');
INSERT INTO companies (name, address)
VALUES ('Buzzshare', '5 Melby Pass');
INSERT INTO companies (name, address)
VALUES ('Skaboo', '1 Spaight Center');
INSERT INTO companies (name, address)
VALUES ('Quire', '0723 Vera Center');
INSERT INTO companies (name, address)
VALUES ('Youtags', '8 Sutteridge Park');
INSERT INTO companies (name, address)
VALUES ('Realbridge', '9610 Emmet Crossing');
INSERT INTO companies (name, address)
VALUES ('Plambee', '727 Troy Center');
INSERT INTO companies (name, address)
VALUES ('Jamia', '11 Karstens Trail');
INSERT INTO companies (name, address)
VALUES ('Brainverse', '5327 Blaine Plaza');
INSERT INTO companies (name, address)
VALUES ('Demimbu', '5262 Delaware Avenue');
INSERT INTO companies (name, address)
VALUES ('Layo', '200 Anniversary Terrace');
INSERT INTO companies (name, address)
VALUES ('Jaloo', '9 Northwestern Lane');
INSERT INTO companies (name, address)
VALUES ('Voomm', '5 Hudson Way');
INSERT INTO companies (name, address)
VALUES ('Fadeo', '5659 Farmco Trail');
INSERT INTO companies (name, address)
VALUES ('Zoonoodle', '48547 Stone Corner Park');
INSERT INTO companies (name, address)
VALUES ('Oodoo', '9070 South Lane');
INSERT INTO companies (name, address)
VALUES ('Brainlounge', '9909 Susan Alley');
INSERT INTO companies (name, address)
VALUES ('Gabcube', '09879 Maywood Parkway');
INSERT INTO companies (name, address)
VALUES ('Chatterpoint', '1 Pepper Wood Lane');
INSERT INTO companies (name, address)
VALUES ('Buzzshare', '7 Elka Terrace');
INSERT INTO companies (name, address)
VALUES ('Agimba', '4 Buena Vista Avenue');
INSERT INTO companies (name, address)
VALUES ('Wikido', '21 Darwin Street');
INSERT INTO companies (name, address)
VALUES ('Gigaclub', '665 Bartillon Pass');
INSERT INTO companies (name, address)
VALUES ('Voomm', '25 Meadow Valley Avenue');
INSERT INTO companies (name, address)
VALUES ('Mybuzz', '370 Namekagon Plaza');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '8134 Mccormick Pass');
INSERT INTO companies (name, address)
VALUES ('Meetz', '375 Basil Park');
INSERT INTO companies (name, address)
VALUES ('Linkbridge', '17 7th Pass');
INSERT INTO companies (name, address)
VALUES ('Quire', '8 Kropf Hill');
INSERT INTO companies (name, address)
VALUES ('Mydo', '5689 Carberry Pass');
INSERT INTO companies (name, address)
VALUES ('Viva', '3323 Michigan Junction');
INSERT INTO companies (name, address)
VALUES ('Eadel', '97 Victoria Point');
INSERT INTO companies (name, address)
VALUES ('Tavu', '97830 Service Court');
INSERT INTO companies (name, address)
VALUES ('Latz', '7 Pond Lane');
INSERT INTO companies (name, address)
VALUES ('Fiveclub', '690 Aberg Plaza');
INSERT INTO companies (name, address)
VALUES ('Zoombeat', '41272 Ridge Oak Circle');
INSERT INTO companies (name, address)
VALUES ('Browsezoom', '790 Meadow Ridge Center');
INSERT INTO companies (name, address)
VALUES ('BlogXS', '4 Bayside Point');
INSERT INTO companies (name, address)
VALUES ('Skyvu', '4 Springs Crossing');
INSERT INTO companies (name, address)
VALUES ('Kazu', '1250 Ronald Regan Plaza');
INSERT INTO companies (name, address)
VALUES ('Lazzy', '9789 Canary Terrace');
INSERT INTO companies (name, address)
VALUES ('Ooba', '1892 Butternut Drive');
INSERT INTO companies (name, address)
VALUES ('Yombu', '33 Hovde Park');
INSERT INTO companies (name, address)
VALUES ('Livepath', '0172 Maple Terrace');
INSERT INTO companies (name, address)
VALUES ('Thoughtworks', '8299 Grayhawk Court');
INSERT INTO companies (name, address)
VALUES ('Innojam', '08849 Heffernan Drive');
INSERT INTO companies (name, address)
VALUES ('Dabtype', '04 Shasta Way');
INSERT INTO companies (name, address)
VALUES ('Livefish', '63791 Sullivan Plaza');
INSERT INTO companies (name, address)
VALUES ('Innotype', '62134 Rutledge Pass');
INSERT INTO companies (name, address)
VALUES ('Centimia', '7710 David Center');
INSERT INTO companies (name, address)
VALUES ('Thoughtworks', '2552 Southridge Park');
INSERT INTO companies (name, address)
VALUES ('Layo', '8 Bartelt Center');
INSERT INTO companies (name, address)
VALUES ('Blognation', '5 Warrior Street');
INSERT INTO companies (name, address)
VALUES ('LiveZ', '53177 Kennedy Center');
INSERT INTO companies (name, address)
VALUES ('Devshare', '16521 Independence Road');
INSERT INTO companies (name, address)
VALUES ('Yoveo', '83 Gerald Plaza');
INSERT INTO companies (name, address)
VALUES ('Mudo', '03 5th Circle');
INSERT INTO companies (name, address)
VALUES ('Chatterbridge', '791 Autumn Leaf Circle');
INSERT INTO companies (name, address)
VALUES ('Browsecat', '24 Del Sol Center');
INSERT INTO companies (name, address)
VALUES ('Meemm', '1 Carberry Drive');
INSERT INTO companies (name, address)
VALUES ('Realcube', '47349 Boyd Plaza');
INSERT INTO companies (name, address)
VALUES ('Midel', '53997 Fair Oaks Street');
INSERT INTO companies (name, address)
VALUES ('Divavu', '7 Muir Point');
INSERT INTO companies (name, address)
VALUES ('Riffwire', '5822 Bartillon Point');
INSERT INTO companies (name, address)
VALUES ('Gevee', '2 Artisan Crossing');
INSERT INTO companies (name, address)
VALUES ('Demizz', '6 Troy Alley');
INSERT INTO companies (name, address)
VALUES ('Realbridge', '5718 Gulseth Parkway');
INSERT INTO companies (name, address)
VALUES ('Yotz', '2991 Mifflin Court');
INSERT INTO companies (name, address)
VALUES ('Dabtype', '92 Kim Drive');
INSERT INTO companies (name, address)
VALUES ('Eamia', '6 Pleasure Terrace');
INSERT INTO companies (name, address)
VALUES ('Youfeed', '2995 Briar Crest Crossing');
INSERT INTO companies (name, address)
VALUES ('Tazz', '821 Steensland Way');
INSERT INTO companies (name, address)
VALUES ('Skinder', '984 Farwell Point');
INSERT INTO companies (name, address)
VALUES ('Edgeify', '358 Forster Court');
INSERT INTO companies (name, address)
VALUES ('Meedoo', '5272 Fairfield Pass');
INSERT INTO companies (name, address)
VALUES ('Latz', '821 Village Green Trail');
INSERT INTO companies (name, address)
VALUES ('Quimba', '3 Knutson Point');
INSERT INTO companies (name, address)
VALUES ('Yombu', '649 Donald Terrace');
INSERT INTO companies (name, address)
VALUES ('Mydeo', '93 Jenifer Point');
INSERT INTO companies (name, address)
VALUES ('Skilith', '03184 Blackbird Center');
INSERT INTO companies (name, address)
VALUES ('Gabtune', '5 Dahle Plaza');
INSERT INTO companies (name, address)
VALUES ('Dynazzy', '020 Moose Way');
INSERT INTO companies (name, address)
VALUES ('Trudoo', '8353 Forest Run Circle');
INSERT INTO companies (name, address)
VALUES ('Voonyx', '7 Hooker Road');
INSERT INTO companies (name, address)
VALUES ('Kimia', '14 Pine View Park');
INSERT INTO companies (name, address)
VALUES ('Tagcat', '06 Eliot Trail');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '13 Declaration Street');
INSERT INTO companies (name, address)
VALUES ('Topicstorm', '3 Cottonwood Street');
INSERT INTO companies (name, address)
VALUES ('Abatz', '206 Parkside Avenue');
INSERT INTO companies (name, address)
VALUES ('Aibox', '3 Sommers Crossing');
INSERT INTO companies (name, address)
VALUES ('Mynte', '2474 Blackbird Point');
INSERT INTO companies (name, address)
VALUES ('Einti', '4066 Northview Terrace');
INSERT INTO companies (name, address)
VALUES ('Yambee', '995 Vera Road');
INSERT INTO companies (name, address)
VALUES ('Meeveo', '88940 Grim Place');
INSERT INTO companies (name, address)
VALUES ('Skipstorm', '59724 Luster Plaza');
INSERT INTO companies (name, address)
VALUES ('Wikivu', '2643 Golf Road');
INSERT INTO companies (name, address)
VALUES ('Agivu', '8 Gale Lane');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '168 Shasta Center');
INSERT INTO companies (name, address)
VALUES ('Jabberstorm', '07 Forest Road');
INSERT INTO companies (name, address)
VALUES ('Divanoodle', '1534 Kennedy Terrace');
INSERT INTO companies (name, address)
VALUES ('Oodoo', '79 Anzinger Court');
INSERT INTO companies (name, address)
VALUES ('Feednation', '67 Lerdahl Lane');
INSERT INTO companies (name, address)
VALUES ('Browseblab', '20906 Lien Point');
INSERT INTO companies (name, address)
VALUES ('Voonyx', '46738 Clemons Trail');
INSERT INTO companies (name, address)
VALUES ('Agimba', '11 Spenser Street');
INSERT INTO companies (name, address)
VALUES ('Eadel', '9421 Veith Trail');
INSERT INTO companies (name, address)
VALUES ('Kwinu', '207 Forest Road');
INSERT INTO companies (name, address)
VALUES ('Zazio', '193 Bonner Point');
INSERT INTO companies (name, address)
VALUES ('Tagfeed', '1281 Messerschmidt Hill');
INSERT INTO companies (name, address)
VALUES ('Vinder', '69724 Mockingbird Way');
INSERT INTO companies (name, address)
VALUES ('Kanoodle', '81059 Loomis Lane');
INSERT INTO companies (name, address)
VALUES ('Ooba', '3726 Artisan Alley');
INSERT INTO companies (name, address)
VALUES ('Photobug', '1 Dennis Avenue');
INSERT INTO companies (name, address)
VALUES ('Geba', '74378 Chive Trail');
INSERT INTO companies (name, address)
VALUES ('Divanoodle', '25 4th Point');
INSERT INTO companies (name, address)
VALUES ('Photolist', '493 Sutteridge Crossing');
INSERT INTO companies (name, address)
VALUES ('Jabbertype', '3 Clarendon Lane');
INSERT INTO companies (name, address)
VALUES ('Yodo', '50677 Gale Crossing');
INSERT INTO companies (name, address)
VALUES ('Kazu', '541 Montana Alley');
INSERT INTO companies (name, address)
VALUES ('Jaloo', '025 Fremont Road');
INSERT INTO companies (name, address)
VALUES ('Npath', '0 Village Green Point');
INSERT INTO companies (name, address)
VALUES ('Avaveo', '43720 Briar Crest Terrace');
INSERT INTO companies (name, address)
VALUES ('Photobug', '2727 Reindahl Circle');
INSERT INTO companies (name, address)
VALUES ('Cogilith', '87256 High Crossing Plaza');
INSERT INTO companies (name, address)
VALUES ('Tagcat', '15 Little Fleur Street');
INSERT INTO companies (name, address)
VALUES ('Gabcube', '148 Clove Crossing');
INSERT INTO companies (name, address)
VALUES ('Meetz', '9 Harper Alley');
INSERT INTO companies (name, address)
VALUES ('Omba', '7461 Vernon Junction');
INSERT INTO companies (name, address)
VALUES ('Wikibox', '2 Warrior Plaza');
INSERT INTO companies (name, address)
VALUES ('Skyndu', '96 Barby Way');
INSERT INTO companies (name, address)
VALUES ('Divavu', '505 Sutherland Place');
INSERT INTO companies (name, address)
VALUES ('Blogtag', '2 Gale Center');
INSERT INTO companies (name, address)
VALUES ('Voolia', '2 Amoth Street');
INSERT INTO companies (name, address)
VALUES ('Blogtags', '97500 Anhalt Parkway');
INSERT INTO companies (name, address)
VALUES ('Dabvine', '0 Dixon Drive');
INSERT INTO companies (name, address)
VALUES ('Trudeo', '282 Blue Bill Park Place');
INSERT INTO companies (name, address)
VALUES ('Blogtag', '885 Golf Alley');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '5106 Londonderry Lane');
INSERT INTO companies (name, address)
VALUES ('Kwideo', '4047 Amoth Road');
INSERT INTO companies (name, address)
VALUES ('Quatz', '8902 Huxley Court');
INSERT INTO companies (name, address)
VALUES ('Aivee', '4 Paget Parkway');
INSERT INTO companies (name, address)
VALUES ('Youbridge', '38609 Golden Leaf Junction');
INSERT INTO companies (name, address)
VALUES ('Einti', '269 Pleasure Hill');
INSERT INTO companies (name, address)
VALUES ('Eabox', '7075 Farwell Road');
INSERT INTO companies (name, address)
VALUES ('Linklinks', '63 Continental Crossing');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '3806 Badeau Hill');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '9 Grasskamp Road');
INSERT INTO companies (name, address)
VALUES ('Yamia', '47 Stuart Lane');
INSERT INTO companies (name, address)
VALUES ('Trudeo', '957 Anthes Drive');
INSERT INTO companies (name, address)
VALUES ('Livetube', '3545 Armistice Crossing');
INSERT INTO companies (name, address)
VALUES ('Dabfeed', '25919 Vermont Crossing');
INSERT INTO companies (name, address)
VALUES ('Edgepulse', '67 Brickson Park Park');
INSERT INTO companies (name, address)
VALUES ('Photofeed', '558 Meadow Ridge Way');
INSERT INTO companies (name, address)
VALUES ('Dynava', '8 Dexter Court');
INSERT INTO companies (name, address)
VALUES ('Demimbu', '0901 Little Fleur Way');
INSERT INTO companies (name, address)
VALUES ('Demivee', '5 Burrows Hill');
INSERT INTO companies (name, address)
VALUES ('Wordtune', '18 Manitowish Junction');
INSERT INTO companies (name, address)
VALUES ('Gigabox', '37 Clove Road');
INSERT INTO companies (name, address)
VALUES ('Twitterbridge', '4520 Ridge Oak Pass');
INSERT INTO companies (name, address)
VALUES ('BlogXS', '08 Buell Alley');
INSERT INTO companies (name, address)
VALUES ('Jayo', '13 Anderson Road');
INSERT INTO companies (name, address)
VALUES ('Quatz', '9 Gerald Point');
INSERT INTO companies (name, address)
VALUES ('Reallinks', '4949 Hollow Ridge Junction');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '203 Saint Paul Park');
INSERT INTO companies (name, address)
VALUES ('Reallinks', '76284 Garrison Pass');
INSERT INTO companies (name, address)
VALUES ('Zoonoodle', '49259 Badeau Pass');
INSERT INTO companies (name, address)
VALUES ('Youtags', '015 Washington Trail');
INSERT INTO companies (name, address)
VALUES ('Dynabox', '2151 Clove Trail');
INSERT INTO companies (name, address)
VALUES ('Miboo', '8330 Southridge Circle');
INSERT INTO companies (name, address)
VALUES ('Fivespan', '0891 Bayside Drive');
INSERT INTO companies (name, address)
VALUES ('Devcast', '1 Bayside Crossing');
INSERT INTO companies (name, address)
VALUES ('Photofeed', '2544 Parkside Crossing');
INSERT INTO companies (name, address)
VALUES ('Skyba', '3 Blackbird Road');
INSERT INTO companies (name, address)
VALUES ('Youopia', '387 Vermont Court');
INSERT INTO companies (name, address)
VALUES ('Realbridge', '19 Hermina Park');
INSERT INTO companies (name, address)
VALUES ('Quaxo', '4 Vahlen Junction');
INSERT INTO companies (name, address)
VALUES ('Mycat', '7119 Coolidge Park');
INSERT INTO companies (name, address)
VALUES ('Zava', '1 Merchant Junction');
INSERT INTO companies (name, address)
VALUES ('Edgeify', '918 Swallow Junction');
INSERT INTO companies (name, address)
VALUES ('Jabbercube', '8 5th Trail');
INSERT INTO companies (name, address)
VALUES ('Zooveo', '0 Ryan Center');
INSERT INTO companies (name, address)
VALUES ('Tagcat', '0075 Corry Pass');
INSERT INTO companies (name, address)
VALUES ('Flipopia', '35 Golf Course Place');
INSERT INTO companies (name, address)
VALUES ('Podcat', '7 Tennyson Road');
INSERT INTO companies (name, address)
VALUES ('Skyndu', '5 Ryan Parkway');
INSERT INTO companies (name, address)
VALUES ('Skiptube', '507 Vidon Point');
INSERT INTO companies (name, address)
VALUES ('Omba', '22987 Springs Lane');
INSERT INTO companies (name, address)
VALUES ('Janyx', '9859 Arapahoe Center');
INSERT INTO companies (name, address)
VALUES ('Meeveo', '08 Holmberg Street');
INSERT INTO companies (name, address)
VALUES ('Twitterworks', '4 Old Shore Street');
INSERT INTO companies (name, address)
VALUES ('Rhynoodle', '87 Buhler Hill');
INSERT INTO companies (name, address)
VALUES ('Zoomlounge', '666 Atwood Alley');
INSERT INTO companies (name, address)
VALUES ('Livepath', '8218 Mosinee Lane');
INSERT INTO companies (name, address)
VALUES ('Jabbercube', '47034 Schiller Circle');
INSERT INTO companies (name, address)
VALUES ('Linkbridge', '62 Fremont Hill');
INSERT INTO companies (name, address)
VALUES ('Devcast', '16 Reindahl Circle');
INSERT INTO companies (name, address)
VALUES ('Rhycero', '417 Maple Wood Park');
INSERT INTO companies (name, address)
VALUES ('Camido', '382 Loftsgordon Avenue');
INSERT INTO companies (name, address)
VALUES ('Centidel', '34 Judy Pass');
INSERT INTO companies (name, address)
VALUES ('Photolist', '5125 Jenna Terrace');
INSERT INTO companies (name, address)
VALUES ('Skyble', '72 Cardinal Road');
INSERT INTO companies (name, address)
VALUES ('Twitterworks', '4160 Iowa Drive');
INSERT INTO companies (name, address)
VALUES ('Gigazoom', '12123 Mallard Trail');
INSERT INTO companies (name, address)
VALUES ('Oyoloo', '86804 Monica Junction');
INSERT INTO companies (name, address)
VALUES ('Avamm', '48 Donald Way');
INSERT INTO companies (name, address)
VALUES ('Mybuzz', '2053 Arizona Junction');
INSERT INTO companies (name, address)
VALUES ('Jaloo', '58 Carey Avenue');
INSERT INTO companies (name, address)
VALUES ('Gabspot', '27 Pawling Lane');
INSERT INTO companies (name, address)
VALUES ('Edgepulse', '1 Killdeer Alley');
INSERT INTO companies (name, address)
VALUES ('Riffpath', '4 Crownhardt Parkway');
INSERT INTO companies (name, address)
VALUES ('Blogtags', '1 Nobel Court');
INSERT INTO companies (name, address)
VALUES ('Edgeblab', '0 South Junction');
INSERT INTO companies (name, address)
VALUES ('Avamm', '5749 Straubel Place');
INSERT INTO companies (name, address)
VALUES ('Camido', '23619 Fieldstone Lane');
INSERT INTO companies (name, address)
VALUES ('Fiveclub', '952 Schlimgen Street');
INSERT INTO companies (name, address)
VALUES ('Yambee', '5978 Chinook Lane');
INSERT INTO companies (name, address)
VALUES ('Gigaclub', '09532 Raven Plaza');
INSERT INTO companies (name, address)
VALUES ('Midel', '6 Tennyson Road');
INSERT INTO companies (name, address)
VALUES ('Feednation', '3 Eliot Crossing');
INSERT INTO companies (name, address)
VALUES ('Lazzy', '189 Mosinee Crossing');
INSERT INTO companies (name, address)
VALUES ('Wordpedia', '6 Burning Wood Place');
INSERT INTO companies (name, address)
VALUES ('Babbleset', '651 Lakewood Gardens Place');
INSERT INTO companies (name, address)
VALUES ('Plajo', '0690 Reinke Avenue');
INSERT INTO companies (name, address)
VALUES ('Aimbo', '44385 Hintze Terrace');
INSERT INTO companies (name, address)
VALUES ('Babbleopia', '204 Lunder Junction');
INSERT INTO companies (name, address)
VALUES ('Divape', '3 Gina Road');
INSERT INTO companies (name, address)
VALUES ('Einti', '2914 Norway Maple Plaza');
INSERT INTO companies (name, address)
VALUES ('Realmix', '2784 Pennsylvania Terrace');
INSERT INTO companies (name, address)
VALUES ('Jaloo', '5 Del Sol Avenue');
INSERT INTO companies (name, address)
VALUES ('Myworks', '727 Claremont Court');
INSERT INTO companies (name, address)
VALUES ('Mymm', '6095 Daystar Way');
INSERT INTO companies (name, address)
VALUES ('Roombo', '677 Duke Center');
INSERT INTO companies (name, address)
VALUES ('Mydeo', '37 Bowman Trail');
INSERT INTO companies (name, address)
VALUES ('Buzzster', '31459 High Crossing Center');
INSERT INTO companies (name, address)
VALUES ('Browseblab', '3361 Rieder Alley');
INSERT INTO companies (name, address)
VALUES ('Skilith', '6 Bayside Plaza');
INSERT INTO companies (name, address)
VALUES ('Viva', '3 Lyons Park');
INSERT INTO companies (name, address)
VALUES ('Tambee', '747 Northview Center');
INSERT INTO companies (name, address)
VALUES ('Kamba', '8396 Oneill Court');
INSERT INTO companies (name, address)
VALUES ('Jabberbean', '820 Blackbird Center');
INSERT INTO companies (name, address)
VALUES ('Fivebridge', '3 Eastwood Lane');
INSERT INTO companies (name, address)
VALUES ('Oyoyo', '6 Schlimgen Way');
INSERT INTO companies (name, address)
VALUES ('Quinu', '17 Sherman Circle');
INSERT INTO companies (name, address)
VALUES ('Tagtune', '815 Manufacturers Hill');
INSERT INTO companies (name, address)
VALUES ('Skinte', '298 Melvin Center');
INSERT INTO companies (name, address)
VALUES ('Twimm', '27 Hintze Junction');
INSERT INTO companies (name, address)
VALUES ('Topicblab', '533 Merry Terrace');
INSERT INTO companies (name, address)
VALUES ('Devshare', '5753 Redwing Terrace');
INSERT INTO companies (name, address)
VALUES ('Mynte', '447 Saint Paul Center');
INSERT INTO companies (name, address)
VALUES ('Devcast', '6 Maywood Lane');
INSERT INTO companies (name, address)
VALUES ('Yodoo', '61330 Warrior Court');
INSERT INTO companies (name, address)
VALUES ('Vitz', '1005 Northfield Park');
INSERT INTO companies (name, address)
VALUES ('Youtags', '3 Hayes Pass');
INSERT INTO companies (name, address)
VALUES ('Zazio', '36 Derek Park');
INSERT INTO companies (name, address)
VALUES ('Youtags', '40551 Nevada Terrace');
INSERT INTO companies (name, address)
VALUES ('Jayo', '3 Scofield Street');
INSERT INTO companies (name, address)
VALUES ('Mycat', '9306 Fuller Hill');
INSERT INTO companies (name, address)
VALUES ('Gevee', '23 Elmside Lane');
INSERT INTO companies (name, address)
VALUES ('Kwimbee', '4 1st Way');
INSERT INTO companies (name, address)
VALUES ('Jatri', '22 Grim Road');
INSERT INTO companies (name, address)
VALUES ('Browsezoom', '16098 Vera Park');
INSERT INTO companies (name, address)
VALUES ('Twitterlist', '95158 Jana Parkway');
INSERT INTO companies (name, address)
VALUES ('Twitterworks', '2 Victoria Street');
INSERT INTO companies (name, address)
VALUES ('Realbuzz', '09152 Golden Leaf Avenue');
INSERT INTO companies (name, address)
VALUES ('Skajo', '88 Surrey Way');
INSERT INTO companies (name, address)
VALUES ('Digitube', '493 Morrow Circle');
INSERT INTO companies (name, address)
VALUES ('Zoovu', '0 Thompson Pass');
INSERT INTO companies (name, address)
VALUES ('Innojam', '6338 Rockefeller Alley');
INSERT INTO companies (name, address)
VALUES ('Eabox', '878 Sage Park');
INSERT INTO companies (name, address)
VALUES ('Wordtune', '0877 Roxbury Plaza');
INSERT INTO companies (name, address)
VALUES ('Eazzy', '75 Loeprich Pass');
INSERT INTO companies (name, address)
VALUES ('Meeveo', '76183 Green Place');
INSERT INTO companies (name, address)
VALUES ('Leexo', '9951 Transport Place');
INSERT INTO companies (name, address)
VALUES ('Chatterbridge', '9483 Becker Pass');
INSERT INTO companies (name, address)
VALUES ('Leenti', '886 Clyde Gallagher Road');
INSERT INTO companies (name, address)
VALUES ('Shuffletag', '214 Delaware Point');
INSERT INTO companies (name, address)
VALUES ('Bubbletube', '63 Knutson Place');
INSERT INTO companies (name, address)
VALUES ('Thoughtsphere', '70 Artisan Avenue');
INSERT INTO companies (name, address)
VALUES ('Jayo', '5092 Rusk Crossing');
INSERT INTO companies (name, address)
VALUES ('Gabtune', '725 Commercial Parkway');
INSERT INTO companies (name, address)
VALUES ('Fanoodle', '3 Sullivan Park');
INSERT INTO companies (name, address)
VALUES ('Topicware', '6 Washington Hill');
INSERT INTO companies (name, address)
VALUES ('Brightbean', '88 Haas Street');
INSERT INTO companies (name, address)
VALUES ('Devpulse', '6 Ludington Road');
INSERT INTO companies (name, address)
VALUES ('Tanoodle', '04211 Ryan Hill');
INSERT INTO companies (name, address)
VALUES ('Yozio', '538 Elka Street');
INSERT INTO companies (name, address)
VALUES ('Meezzy', '74330 Melby Trail');
INSERT INTO companies (name, address)
VALUES ('Aimbu', '708 Anniversary Park');
INSERT INTO companies (name, address)
VALUES ('Zazio', '56627 Mendota Avenue');
INSERT INTO companies (name, address)
VALUES ('Livepath', '8882 Golf Course Junction');
INSERT INTO companies (name, address)
VALUES ('Zazio', '08271 Dayton Lane');
INSERT INTO companies (name, address)
VALUES ('Talane', '35030 Leroy Way');
INSERT INTO companies (name, address)
VALUES ('Mydo', '7963 Scoville Point');
INSERT INTO companies (name, address)
VALUES ('Quamba', '30112 Schmedeman Drive');
INSERT INTO companies (name, address)
VALUES ('Trupe', '1798 Grim Lane');
INSERT INTO companies (name, address)
VALUES ('Wikizz', '83 4th Junction');
INSERT INTO companies (name, address)
VALUES ('Midel', '88 Pennsylvania Trail');
INSERT INTO companies (name, address)
VALUES ('Photofeed', '7502 Loftsgordon Alley');
INSERT INTO companies (name, address)
VALUES ('Aimbu', '7 Bunting Trail');
INSERT INTO companies (name, address)
VALUES ('Leenti', '184 Red Cloud Crossing');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '00 Hazelcrest Road');
INSERT INTO companies (name, address)
VALUES ('Quamba', '4 Kropf Parkway');
INSERT INTO companies (name, address)
VALUES ('Janyx', '7 Express Drive');
INSERT INTO companies (name, address)
VALUES ('Gabcube', '049 Gerald Parkway');
INSERT INTO companies (name, address)
VALUES ('Zoombeat', '87 Katie Drive');
INSERT INTO companies (name, address)
VALUES ('Flipopia', '96253 Old Shore Circle');
INSERT INTO companies (name, address)
VALUES ('Yodoo', '1 Oak Alley');
INSERT INTO companies (name, address)
VALUES ('Oba', '6724 Manley Plaza');
INSERT INTO companies (name, address)
VALUES ('Realmix', '862 Mitchell Way');
INSERT INTO companies (name, address)
VALUES ('Divape', '014 Oxford Avenue');
INSERT INTO companies (name, address)
VALUES ('Kimia', '94780 Namekagon Place');
INSERT INTO companies (name, address)
VALUES ('Mycat', '0 Moulton Hill');
INSERT INTO companies (name, address)
VALUES ('Thoughtblab', '70 Gale Parkway');
INSERT INTO companies (name, address)
VALUES ('Skilith', '1 Judy Junction');
INSERT INTO companies (name, address)
VALUES ('Zoomcast', '6983 Thompson Court');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '258 Rockefeller Parkway');
INSERT INTO companies (name, address)
VALUES ('Rhyloo', '219 Lukken Terrace');
INSERT INTO companies (name, address)
VALUES ('Skinix', '76 Green Point');
INSERT INTO companies (name, address)
VALUES ('Topicblab', '72633 Arrowood Crossing');
INSERT INTO companies (name, address)
VALUES ('Yakijo', '0854 Manufacturers Terrace');
INSERT INTO companies (name, address)
VALUES ('Zazio', '110 Shopko Center');
INSERT INTO companies (name, address)
VALUES ('LiveZ', '0 Lakewood Pass');
INSERT INTO companies (name, address)
VALUES ('Edgewire', '79 Huxley Point');
INSERT INTO companies (name, address)
VALUES ('Ozu', '22823 Shoshone Center');
INSERT INTO companies (name, address)
VALUES ('Aimbo', '4599 Raven Park');
INSERT INTO companies (name, address)
VALUES ('Mynte', '19 Merrick Pass');
INSERT INTO companies (name, address)
VALUES ('Meedoo', '055 Lukken Junction');
INSERT INTO companies (name, address)
VALUES ('Thoughtbeat', '6647 Myrtle Avenue');
INSERT INTO companies (name, address)
VALUES ('Roodel', '5 Monument Trail');
INSERT INTO companies (name, address)
VALUES ('Meedoo', '2 Leroy Road');
INSERT INTO companies (name, address)
VALUES ('Vidoo', '06 Swallow Court');
INSERT INTO companies (name, address)
VALUES ('Bubblemix', '1620 Lawn Trail');
INSERT INTO companies (name, address)
VALUES ('Gigazoom', '22 Pond Place');
INSERT INTO companies (name, address)
VALUES ('Twiyo', '72 Hoffman Hill');
INSERT INTO companies (name, address)
VALUES ('Zoomzone', '54 Darwin Point');
INSERT INTO companies (name, address)
VALUES ('Pixonyx', '890 Manitowish Parkway');
INSERT INTO companies (name, address)
VALUES ('Leenti', '5825 Dennis Junction');
INSERT INTO companies (name, address)
VALUES ('Oozz', '7 Summerview Junction');
INSERT INTO companies (name, address)
VALUES ('Muxo', '3861 Nova Parkway');
INSERT INTO companies (name, address)
VALUES ('Tambee', '64423 Bluestem Alley');
INSERT INTO companies (name, address)
VALUES ('Chatterbridge', '34 Lake View Court');
INSERT INTO companies (name, address)
VALUES ('Skiptube', '71040 Daystar Hill');
INSERT INTO companies (name, address)
VALUES ('Meetz', '4 Mallory Street');
INSERT INTO companies (name, address)
VALUES ('Linkbuzz', '38 Hanover Lane');
INSERT INTO companies (name, address)
VALUES ('Wikivu', '1410 Montana Junction');
INSERT INTO companies (name, address)
VALUES ('Blognation', '488 Bluestem Alley');
INSERT INTO companies (name, address)
VALUES ('Yakidoo', '62 Grasskamp Way');
INSERT INTO companies (name, address)
VALUES ('Leenti', '995 Village Circle');
INSERT INTO companies (name, address)
VALUES ('Centidel', '902 Spohn Court');
INSERT INTO companies (name, address)
VALUES ('Mynte', '8356 Bowman Court');
INSERT INTO companies (name, address)
VALUES ('Oozz', '56 Vidon Trail');
INSERT INTO companies (name, address)
VALUES ('Jabbertype', '97 Melvin Circle');
INSERT INTO companies (name, address)
VALUES ('Pixoboo', '88 Rutledge Way');
INSERT INTO companies (name, address)
VALUES ('Tagchat', '02502 Debs Street');
INSERT INTO companies (name, address)
VALUES ('Browsedrive', '51568 Jay Parkway');
INSERT INTO companies (name, address)
VALUES ('Jayo', '9076 Arapahoe Street');
INSERT INTO companies (name, address)
VALUES ('Blogtags', '850 Messerschmidt Junction');
INSERT INTO companies (name, address)
VALUES ('Izio', '8952 Merrick Alley');
INSERT INTO companies (name, address)
VALUES ('Lajo', '285 Lukken Park');
INSERT INTO companies (name, address)
VALUES ('Izio', '43 Pearson Hill');
INSERT INTO companies (name, address)
VALUES ('Bluejam', '026 Farragut Junction');
INSERT INTO companies (name, address)
VALUES ('Jaxspan', '511 Hallows Plaza');
INSERT INTO companies (name, address)
VALUES ('Browseblab', '81 Mandrake Avenue');
INSERT INTO companies (name, address)
VALUES ('Podcat', '9931 Hovde Pass');
INSERT INTO companies (name, address)
VALUES ('Quamba', '7028 Corry Circle');
INSERT INTO companies (name, address)
VALUES ('Brainsphere', '70422 Carey Junction');
INSERT INTO companies (name, address)
VALUES ('Flipbug', '6 Debra Park');
INSERT INTO companies (name, address)
VALUES ('Riffwire', '35336 Straubel Junction');
INSERT INTO companies (name, address)
VALUES ('Yakitri', '97 Claremont Avenue');
INSERT INTO companies (name, address)
VALUES ('Trupe', '08 Bayside Drive');
INSERT INTO companies (name, address)
VALUES ('Minyx', '379 Sloan Parkway');
INSERT INTO companies (name, address)
VALUES ('Flashspan', '3076 Center Street');
INSERT INTO companies (name, address)
VALUES ('Feednation', '877 Butternut Junction');
INSERT INTO companies (name, address)
VALUES ('Quamba', '5 Acker Court');
INSERT INTO companies (name, address)
VALUES ('Geba', '218 Prairieview Alley');
INSERT INTO companies (name, address)
VALUES ('Yambee', '4 Sunbrook Place');
INSERT INTO companies (name, address)
VALUES ('Flipstorm', '499 Commercial Point');
INSERT INTO companies (name, address)
VALUES ('Mybuzz', '73 Messerschmidt Alley');
INSERT INTO companies (name, address)
VALUES ('Youspan', '47867 Troy Alley');
INSERT INTO companies (name, address)
VALUES ('InnoZ', '30 Canary Circle');
INSERT INTO companies (name, address)
VALUES ('Lajo', '4346 Forest Dale Way');
INSERT INTO companies (name, address)
VALUES ('Eidel', '5298 Haas Street');
INSERT INTO companies (name, address)
VALUES ('Blognation', '44567 Charing Cross Place');
INSERT INTO companies (name, address)
VALUES ('Linktype', '3 Upham Parkway');
INSERT INTO companies (name, address)
VALUES ('Kanoodle', '470 Carberry Plaza');
INSERT INTO companies (name, address)
VALUES ('Gigazoom', '67 Susan Avenue');
INSERT INTO companies (name, address)
VALUES ('Reallinks', '4 Mariners Cove Center');
INSERT INTO companies (name, address)
VALUES ('Flashset', '7017 Bay Junction');
INSERT INTO companies (name, address)
VALUES ('Voomm', '8 Heffernan Circle');
INSERT INTO companies (name, address)
VALUES ('Pixonyx', '5554 Armistice Place');
INSERT INTO companies (name, address)
VALUES ('Feedfire', '449 Johnson Point');
INSERT INTO companies (name, address)
VALUES ('DabZ', '293 Hallows Hill');
INSERT INTO companies (name, address)
VALUES ('Tavu', '26 Hoffman Hill');
INSERT INTO companies (name, address)
VALUES ('Meevee', '5 4th Lane');
INSERT INTO companies (name, address)
VALUES ('Bubbletube', '7 Oxford Drive');
INSERT INTO companies (name, address)
VALUES ('Digitube', '8 Killdeer Crossing');
INSERT INTO companies (name, address)
VALUES ('Bubblebox', '6 Shasta Crossing');
INSERT INTO companies (name, address)
VALUES ('Divavu', '80 Shelley Terrace');
INSERT INTO companies (name, address)
VALUES ('Roomm', '59080 Utah Point');
INSERT INTO companies (name, address)
VALUES ('Fliptune', '18345 Lighthouse Bay Court');
INSERT INTO companies (name, address)
VALUES ('Devpulse', '140 Spenser Plaza');
INSERT INTO companies (name, address)
VALUES ('Skyba', '15144 Marquette Pass');
INSERT INTO companies (name, address)
VALUES ('Innojam', '70 Bultman Plaza');
INSERT INTO companies (name, address)
VALUES ('Abatz', '211 High Crossing Park');
INSERT INTO companies (name, address)
VALUES ('Oyoyo', '5862 Service Place');
INSERT INTO companies (name, address)
VALUES ('Yodoo', '8 Hayes Crossing');
INSERT INTO companies (name, address)
VALUES ('Youbridge', '2 Lighthouse Bay Avenue');
INSERT INTO companies (name, address)
VALUES ('Nlounge', '09374 Randy Center');
INSERT INTO companies (name, address)
VALUES ('Divavu', '11285 Charing Cross Drive');
INSERT INTO companies (name, address)
VALUES ('Quaxo', '0982 Messerschmidt Point');
INSERT INTO companies (name, address)
VALUES ('Blogspan', '74 Bellgrove Drive');
INSERT INTO companies (name, address)
VALUES ('Photojam', '342 New Castle Road');
INSERT INTO companies (name, address)
VALUES ('Quamba', '74005 Park Meadow Point');
INSERT INTO companies (name, address)
VALUES ('Ooba', '83140 Golf Crossing');
INSERT INTO companies (name, address)
VALUES ('Katz', '33 Arizona Parkway');
INSERT INTO companies (name, address)
VALUES ('Wikivu', '619 Express Street');
INSERT INTO companies (name, address)
VALUES ('Oyoyo', '48863 Sullivan Hill');
INSERT INTO companies (name, address)
VALUES ('Einti', '17 Amoth Park');
INSERT INTO companies (name, address)
VALUES ('Vimbo', '33 Atwood Circle');
INSERT INTO companies (name, address)
VALUES ('Yoveo', '2840 Everett Street');
INSERT INTO companies (name, address)
VALUES ('Layo', '72 Jana Circle');
INSERT INTO companies (name, address)
VALUES ('Reallinks', '84220 Melby Point');
INSERT INTO companies (name, address)
VALUES ('Janyx', '138 Sachs Avenue');